/*
 *
 * ** NOTE ---- THIS IS ONLY DEVELOPMENT PAGES ---- **
 * SO THEY WILL NOT BE INCLUDED IN THE BUILD.
 *
 * THESE PAGES DATA NOT PROCESSED WITH `processPath` function.
 * SO MAKE SURE YOUR WRITE PATH AND `PARAMS(if any)` PROPERLY.
 */

const DEVELOPMENT_ONLY_PAGES = [];

module.exports = DEVELOPMENT_ONLY_PAGES;
